name: robot-env
channels:
- conda-forge
- https://repo.continuum.io/pkgs/main/win-64/

dependencies:
- ffmpeg
- python = 3
- jupyter
- matplotlib
- pandas
- numpy

- pip:
  - tqdm
  - imageio
  - pillow
  - opencv-python
  - scikit-learn = 0.18.0
